export const SEARCH_BY_NAME="SEARCH";
export const GET_COUNTRIES="GET_COUNTRIES"
export const GET_ACTIVITIES="GET_ACTIVITIES"
export const GET_COUNTRY_DETAIL="GET_COUNTRY_DETAIL"
export const FILTER_BY_CONTINENT="FILTER_BY_CONTINENT"
export const FILTER_BY_ACTIVITY="FILTER_BY_ACTIVITY"
export const SORT="SORT"
export const PAGINATE="PAGINATE"

